CREATE TABLE NIVEL (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(50) NOT NULL
);

INSERT INTO NIVEL (NOMBRE) VALUES
('1 SEMESTRE'),
('2 SEMESTRE'),
('3 SEMESTRE'),
('4 SEMESTRE'),
('5 SEMESTRE'),
('6 SEMESTRE'),
('7 SEMESTRE'),
('8 SEMESTRE'),
('9 SEMESTRE'),
('10 SEMESTRE');

CREATE TABLE CARRERA (
  ID SERIAL PRIMARY KEY,
  CODIGO VARCHAR(10) NOT NULL,
  MODALIDAD SMALLINT CHECK (modalidad BETWEEN 0 AND 2) NOT NULL, -- 0 = PRESENCIAL ; 1 = VIRTUAL ; 2 = HIBRIDO
  NOMBRE VARCHAR(63) NOT NULL
);

INSERT INTO CARRERA (CODIGO, MODALIDAD, NOMBRE) VALUES
('185', 0, 'INGENIERIA EN REDES Y TELECOMUNICACIONES'),
('183', 0, 'INGENIERIA INFORMATICA'),
('184', 0, 'INGENIERIA EN SISTEMAS');


CREATE TABLE DIA(
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(15) NOT NULL
);

INSERT INTO DIA (NOMBRE) VALUES
('LUNES'),
('MARTES'),
('MIERCOLES'),
('JUEVES'),
('VIERNES'),
('SABADO');


CREATE TABLE HORA(
  ID SERIAL PRIMARY KEY,
  HR_INICIO TIME NOT NULL, 
  HR_FIN TIME NOT NULL
);

INSERT INTO HORA (HR_INICIO,HR_FIN) VALUES
('07:00:00', '08:30:00'),
('07:00:00', '09:15:00'),
('08:30:00', '10:00:00'),
('09:15:00', '11:15:00'),
('10:00:00', '11:30:00');

CREATE TABLE GESTION(
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(25) NOT NULL
);

INSERT INTO GESTION (NOMBRE) VALUES
('1-2025');

CREATE TABLE DOCENTE(
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(125) NOT NULL,
  TELEFONO BIGINT NULL,
  CI INT NOT NULL
);

INSERT INTO DOCENTE(NOMBRE,TELEFONO,CI) VALUES
('FRANCO MIGUEL URIBE PAZ',70000001,9000001),
('LUIS ANGEL ZAPATA CARDONA',70000002,9000002),
('ENRIQUE SUBIETA ARREDONDO',70000003,9000003),
('VICTOR MANUEL FERNANDEZ CUELLAR',70000004,9000004),
('JOSE MIGUEL ORTUÑO PEREZ',70000005,9000005);

CREATE TABLE MODULO(
  ID SERIAL PRIMARY KEY,
  NRO_MODULO SMALLINT NOT NULL
);

INSERT INTO MODULO(NRO_MODULO) VALUES
(236);

CREATE TABLE MATERIA(
  ID SERIAL PRIMARY KEY,
  CREDITO SMALLINT NOT NULL,
  ES_ELECTIVA BOOLEAN NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  SIGLA VARCHAR(15) NOT NULL
);

INSERT INTO MATERIA(CREDITO,ES_ELECTIVA,NOMBRE,SIGLA) VALUES
(10,FALSE,'INTRODUCCION A LA INFORMATICA','INF110'),
(10,FALSE,'ESTRUCTURAS DISCRETAS','INF119'),
(10,FALSE,'FISICA I','FIS100'),
(10,FALSE,'INGLES TECNICO I','LIN100'),
(10,FALSE,'CALCULO I','MAT101'),

(10,FALSE,'ALGEBRA LINEAL','MAT103'),
(10,FALSE,'PROGRAMACION I','INF120'),
(10,FALSE,'CALCULO I','MAT102'),
(10,FALSE,'FISICA II','FIS102'),
(10,FALSE,'INGLES TECNICO II','LIN101'),

(10,FALSE,'ARQUITECTURA DE COMPUTADORAS','INF211'),
(10,FALSE,'PROGRAMACION II','INF210'),
(10,FALSE,'ADMINISTRACION','ADM100'),
(10,FALSE,'FISICA III','FIS200'),
(10,FALSE,'ECUACIONES DIFERENCIALES','MAT207'),

(10,FALSE,'PROBABILIDAD Y ESTADISTICA I','MAT202'),
(10,FALSE,'CONTABILIDAD','ADM200'),
(10,FALSE,'PROGRAMACION ENSAMBLADOR','INF221'),
(10,FALSE,'ESTRUCTURA DE DATOS I','INF220'),
(10,FALSE,'METODOS NUMERICOS','MAT205'),

(10,FALSE,'LENGUAJES FORMALES','INF319'),
(10,FALSE,'PROGRAMACION LOGICA Y FUNCIONAL','INF318'),
(10,FALSE,'BASE DE DATROS I','INF312'),
(10,FALSE,'ESTRUCTURA DE DATOS II','INF310'),
(10,FALSE,'PROBABILIDAD Y ESTADISTIVA II','MAT302'),

(10,FALSE,'BASE DE DATOS II','INF322'),
(10,FALSE,'INVESTIGACION OPERATIVA I','MAT329'),
(10,FALSE,'COMPILADORES','INF329'),
(10,FALSE,'SISTEMAS OPERATIVOS I','INF323'),
(10,FALSE,'SISTEMAS DE INFORMACION I','INF342'),

(10,FALSE,'REDES I','INF433'),
(10,FALSE,'SISTEMAS OPERATIVOS II','INF413'),
(10,FALSE,'INTELIGENCIA ARTIFICIAL','INF418'),
(10,FALSE,'SISTEMAS DE INFORMACION II','INF412'),
(10,FALSE,'INVESTIGACION OPERATIVA II','MAT419'),

(10,FALSE,'INGENIERIA DE SOFTWARE I','INF422'),
(10,FALSE,'REDES II','INF423'),
(10,FALSE,'SISTEMAS DE INFORMACION GEOGRAFICA','INF442'),
(10,FALSE,'PREPARACION Y EVALUACION DE PROYECTO','ECO449'),
(10,FALSE,'SISTEMAS EXPERTOS','INF428'),

(10,FALSE,'INGENIERIA DE SOFTWARE II','INF512'),
(10,FALSE,'ARQUITECTURA DE SOFTWARE','INF552'),
(10,FALSE,'TECNOLOGIA WEB','INF513'),
(10,FALSE,'TALLER DE GRADO','INF511'),

(10,FALSE,'MODALIDAD DE GRADUACION ','GRLM001'),

--ELECTIVAS
(10,TRUE,'CRIPTOGRAFICA Y SEGURIDAD','ELC107'),
(10,TRUE,'SISTEMAS DISTRIBUIDOS','ELC105'),
(10,TRUE,'TOPICOS AVANZADOS DE PROGRAMACION','ELC103'),
(10,TRUE,'PROGRAMACION GRAFICA','ELC102');

CREATE TABLE PLAN_ESTUDIO(
  ID SERIAL PRIMARY KEY,
  CODIGO VARCHAR(10) NOT NULL,
  CARRERA_ID INT NOT NULL,
  CONSTRAINT FK_CARRERA FOREIGN KEY (CARRERA_ID) REFERENCES CARRERA(ID)
);

INSERT INTO PLAN_ESTUDIO(CODIGO,CARRERA_ID) VALUES
(1,1),-- 
(2,2),
(3,1);

CREATE TABLE MATERIA_PLAN_ESTUDIO(
  ID SERIAL PRIMARY KEY,
  MATERIA_ID INT NOT NULL,
  NIVEL_ID INT NOT NULL,
  PLAN_ESTUDIO_ID INT NOT NULL,
  CONSTRAINT FK_MATERIA FOREIGN KEY (MATERIA_ID) REFERENCES MATERIA(ID),
  CONSTRAINT FK_NIVEL FOREIGN KEY (NIVEL_ID) REFERENCES NIVEL(ID),
  CONSTRAINT FK_PLAN_ESTUDIO FOREIGN KEY (PLAN_ESTUDIO_ID) REFERENCES PLAN_ESTUDIO(ID)
);

INSERT INTO MATERIA_PLAN_ESTUDIO (MATERIA_ID,NIVEL_ID,PLAN_ESTUDIO_ID) VALUES
--PRIMER SEMESTRE
(1,1,1),
(2,1,1),
(3,1,1),
(4,1,1),
(5,1,1),
--SEGUNDO SEMESTRE
(6,2,1),
(7,2,1),
(8,2,1),
(9,2,1),
(10,2,1),
--TERCERO SEMESTRE
(11,3,1),
(12,3,1),
(13,3,1),
(14,3,1),
(15,3,1),
--CUARTO SEMESTRE
(16,4,1),
(17,4,1),
(18,4,1),
(19,4,1),
(20,4,1),
--QUINTO SEMESTRE
(21,5,1),
(22,5,1),
(23,5,1),
(24,5,1),
(25,5,1),
--SEXTO SEMESTRE
(26,6,1),
(27,6,1),
(28,6,1),
(29,6,1),
(30,6,1),
--SEPTIMO SEMESTRE
(31,7,1),
(32,7,1),
(33,7,1),
(34,7,1),
(35,7,1),
--OCTAVO SEMESTRE
(36,8,1),
(37,8,1),
(38,8,1),
(39,8,1),
(40,8,1),
--NOVENO SEMESTRE
(41,9,1),
(42,9,1),
(43,9,1),
(44,9,1),
--DECIMO SEMESTRE
(45,10,1);

CREATE TABLE PREREQUISITO(
  MATERIA_PLAN_ESTUDIO_ID INT NOT NULL,
  REQUISITO_ID INT NOT NULL,
  PRIMARY KEY(MATERIA_PLAN_ESTUDIO_ID, REQUISITO_ID),
  CONSTRAINT FK_MATERIA_PLAN_ESTUDIO FOREIGN KEY(MATERIA_PLAN_ESTUDIO_ID) REFERENCES MATERIA_PLAN_ESTUDIO(ID),
  CONSTRAINT FK_REQUISITO FOREIGN KEY(REQUISITO_ID) REFERENCES MATERIA_PLAN_ESTUDIO(ID),
  CONSTRAINT CHK_NO_AUTOREFERENCIA CHECK (MATERIA_PLAN_ESTUDIO_ID <> REQUISITO_ID)
);

CREATE TABLE HORA_DIA(
  ID SERIAL PRIMARY KEY,
  DIA_ID INT NOT NULL,
  HORA_ID INT NOT NULL,
  CONSTRAINT FK_DIA FOREIGN KEY (DIA_ID) REFERENCES DIA(ID),
  CONSTRAINT FK_HORA FOREIGN KEY (HORA_ID) REFERENCES HORA(ID)
);

INSERT INTO HORA_DIA (DIA_ID,HORA_ID) VALUES
(1,1),
(1,2),
(1,3),
(1,4);

CREATE TABLE HORARIO(
  ID SERIAL PRIMARY KEY
);

INSERT INTO HORARIO (ID)
SELECT nextval('horario_id_seq') FROM generate_series(1,10);

CREATE TABLE HORA_DIA_HORARIO(
  ID SERIAL PRIMARY KEY,
  HORA_DIA_ID INT NOT NULL,
  HORARIO_ID INT NOT NULL,
  CONSTRAINT FK_HORA_DIA FOREIGN KEY (HORA_DIA_ID) REFERENCES HORA_DIA(ID),
  CONSTRAINT FK_HORARIO FOREIGN KEY (HORARIO_ID) REFERENCES HORARIO(ID)
);

-- Se mueve la tabla ALUMNO antes de INSCRIPCION para resolver el error de dependencia.
CREATE TABLE ALUMNO(
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(60) NOT NULL,
  PPA NUMERIC(10,2) NOT NULL,
  TELEFONO INT NULL,
  REGISTRO INT NOT NULL
);

CREATE TABLE INSCRIPCION(
  ID SERIAL PRIMARY KEY,
  FECHA DATE NOT NULL,
  ALUMNO_ID INT NOT NULL,
  CONSTRAINT FK_ALUMNO FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNO(ID)
);

CREATE TABLE HORARIO_MATERIA(
  ID SERIAL PRIMARY KEY,
  CUPOS_DISPONIBLES SMALLINT NOT NULL,
  CUPOS_TOTAL SMALLINT NOT NULL,
  NRO_AULA INT,
  GESTION_ID INT NOT NULL,
  MATERIA_PLAN_ESTUDIO_ID INT NOT NULL,
  MODULO_ID INT NOT NULL,
  DOCENTE_ID INT NULL,
  HORARIO_ID INT NOT NULL,
  CONSTRAINT FK_GESTION FOREIGN KEY (GESTION_ID) REFERENCES GESTION(ID),
  CONSTRAINT FK_MATERIA_PLAN_ESTUDIO FOREIGN KEY (MATERIA_PLAN_ESTUDIO_ID) REFERENCES MATERIA_PLAN_ESTUDIO(ID),
  CONSTRAINT FK_MODULO FOREIGN KEY (MODULO_ID) REFERENCES MODULO(ID),
  CONSTRAINT FK_DOCENTE FOREIGN KEY (DOCENTE_ID) REFERENCES DOCENTE(ID),
  CONSTRAINT FK_HORARIO FOREIGN KEY (HORARIO_ID) REFERENCES HORARIO(ID)
);

CREATE TABLE HORARIO_MATERIA_INSCRIPCION (
  ID SERIAL PRIMARY KEY,
  HORARIO_MATERIA_ID INT NOT NULL,
  INSCRIPCION_ID INT NOT NULL,
  CONSTRAINT FK_HMI_HM FOREIGN KEY (HORARIO_MATERIA_ID) REFERENCES HORARIO_MATERIA(ID),
  CONSTRAINT FK_HMI_INS FOREIGN KEY (INSCRIPCION_ID) REFERENCES INSCRIPCION(ID)
);
